### PR TITLE
Optimize attach `pkd`

### PR DESCRIPTION
**Pull request by und3fined**
Attach to process name maybe not work.
I find `pkd` pid and direct attach to it.

### CODE REVIEW

**Comment by ChiChou** [comment]
What do you mean "attach to process name maybe not work"?

Your patch is actually introducing a bug, if there is any other app name that ends with pkd

**Comment by ChiChou** [comment]
The only scenario I could think of to break attach is that `pkd` is currently not running. The right solution is to spawn `launchctl kickstart` with the right parameters, or use frida to prewarm it throuth XPC

**Comment by und3fined** [comment]
Thanks for reply, but with i can't attach via `dev.attach('pkd')`.
I check process with `ps aux | grep pkd`. It running

I'll try prewarm it through XPC

**Comment by und3fined** [comment]
And, maybe need more way run launch plugin. I'm stuck at `NSExtension.extensionWithIdentifier_error_(identifier, NULL);`

**Comment by ChiChou** [comment]
I don't have a jailbreak environment that is higher than iOS 14 at the moment. In the past, frida was not able to spawn an extension process directly due to XPC framework limits. Somehow now it looks possible to pause them during early initialization. 

Can you confirm that this strategy is working for you?

1. Manually get the extension's executable path
2. Try spawn it with `frida -U -f /var/mobile/XXXXXXX`
3. See if it pauses at the entry

If it works, we don't need this pkd workaround anymore

**Comment by und3fined** [comment]
> Manually get the extension's executable path

It's worked there, but need --pause params

Screenshot 2023-03-30 at 17 08 09

**Comment by ChiChou** [comment]
That's nice. We can switch

**Comment by ChiChou** [comment]
Maybe next week I'll write a version without pkd patch

**Comment by und3fined** [comment]
Thanks for reply and your suggest. I complete my script for private use

**Pull request closed without merging**
