### PR TITLE
update frida to latest version

### PR DESCRIPTION
**Pull request by itsmylife44**

### CODE REVIEW

**Comment by ChiChou** [comment]
It's not a major version change. Did you meet any compatibility issue?

**Comment by itsmylife44** [comment]
it seems that even with the latest version , dumping big applications with many plugins/frameworks crashes and does not go forward .

**Comment by itsmylife44** [comment]
```patch PluginKit validation
dump extensions```

blocking here

**Comment by ChiChou** [comment]
Merge to fix the dependency error. However, the bugs you encountered (including https://github.com/ChiChou/bagbak/issues/86) are not related to this

**Pull request merged**
